; Standalone qualification for the MIDI Studio device-support package.

[platformio]
default_envs = dev
src_dir = qualification

[env]
framework = arduino
platform = teensy
board = teensy41
board_build.f_cpu = 450000000L

build_flags =
    -D USB_MIDI_SERIAL
    -D TEENSY_OPT_SMALLEST_CODE
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_LVGL_H_INCLUDE_SIMPLE

[env:dev]
lib_deps =
    ms-device-support=symlink://.
    oc-framework=symlink://../../open-control/framework
    oc-hal-common=symlink://../../open-control/hal-common
    oc-hal-teensy=symlink://../../open-control/hal-teensy
    oc-ui-lvgl=symlink://../../open-control/ui-lvgl

[env:release]
lib_deps =
    ms-device-support=symlink://.
    oc-framework=https://github.com/open-control/framework.git#3b8a182422bb1183e5930da0eeb53e584a570dbb
    oc-hal-common=https://github.com/open-control/hal-common.git#e3aa784055554922d130bba8065422d11a7dcd02
    oc-hal-teensy=https://github.com/open-control/hal-teensy.git#f3c49f75aeda045c28d698bca0ec450e20a56838
    oc-ui-lvgl=https://github.com/open-control/ui-lvgl.git#04eeef42aee5b88863a22736af06b52c5815aed1
