; Standalone qualification for the MIDI Studio device-support package.

[platformio]
default_envs = dev
src_dir = qualification

[env]
framework = arduino
platform = teensy
board = teensy41
board_build.f_cpu = 450000000L

build_flags =
    -D USB_MIDI_SERIAL
    -D TEENSY_OPT_SMALLEST_CODE
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_LVGL_H_INCLUDE_SIMPLE

[env:dev]
lib_deps =
    ms-device-support=symlink://.
    oc-framework=symlink://../../open-control/framework
    oc-hal-common=symlink://../../open-control/hal-common
    oc-hal-teensy=symlink://../../open-control/hal-teensy
    oc-ui-lvgl=symlink://../../open-control/ui-lvgl

[env:release]
lib_deps =
    ms-device-support=symlink://.
    oc-framework=https://github.com/open-control/framework.git#f6be8f51ff80f5f5f82ec7c589a984730445f9b4
    oc-hal-common=https://github.com/open-control/hal-common.git#e3aa784055554922d130bba8065422d11a7dcd02
    oc-hal-teensy=https://github.com/open-control/hal-teensy.git#713e5aa6fbdc318a9d517ddb0e7ec3635ca93da5
    oc-ui-lvgl=https://github.com/open-control/ui-lvgl.git#3884a808e8478009e10d70c74cd7f7050e619803
