; Standalone qualification for the MIDI Studio device-support package.

[platformio]
default_envs = dev
src_dir = qualification

[env]
framework = arduino
platform = teensy
board = teensy41
board_build.f_cpu = 450000000L

build_flags =
    -D USB_MIDI_SERIAL
    -D TEENSY_OPT_SMALLEST_CODE
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_LVGL_H_INCLUDE_SIMPLE

[env:dev]
lib_deps =
    ms-device-support=symlink://.
    oc-framework=symlink://../../open-control/framework
    oc-hal-common=symlink://../../open-control/hal-common
    oc-hal-teensy=symlink://../../open-control/hal-teensy
    oc-ui-lvgl=symlink://../../open-control/ui-lvgl

[env:release]
lib_deps =
    ms-device-support=symlink://.
    oc-framework=https://github.com/open-control/framework.git#24037dcee919f955cb3626b92853fd963ead87aa
    oc-hal-common=https://github.com/open-control/hal-common.git#5567103c878e3c9e5be8929d1301a15b4bfa02aa
    oc-hal-teensy=https://github.com/open-control/hal-teensy.git#617769b086b385aa3a035611e217efda3144eb57
    oc-ui-lvgl=https://github.com/open-control/ui-lvgl.git#4d6276976b7db31f4af0b3dd6ffc8c8589cb6dba
